-- 1. PROFILES (Extends auth.users)
-- This table mirrors the Supabase Auth user table but adds our app-specific fields
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text check (role in ('owner', 'user')), -- Enforce roles
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. TRIGGER for New User Signup
-- Automatically creates a profile entry when a user signs up via Supabase Auth
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    COALESCE(new.raw_user_meta_data->>'role', 'user') -- Default to user if not specified
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. PARKS
create table public.parks (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) not null,
  name text not null,
  location text not null,
  latitude double precision default 0.0,
  longitude double precision default 0.0,
  total_slots integer not null default 0,
  hourly_rate double precision default 0.0,
  camera_rtsp_url_encrypted text,
  payment_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. SLOTS
create table public.slots (
  id bigint generated by default as identity primary key,
  park_id bigint references public.parks(id) on delete cascade not null,
  slot_number text not null,
  is_occupied boolean default false,
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- 5. BOOKINGS
create table public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  slot_id bigint references public.slots(id) not null,
  start_time timestamp with time zone default timezone('utc'::text, now()),
  end_time timestamp with time zone,
  status text default 'active', -- active, completed, cancelled
  amount double precision default 0.0,
  payment_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. LOGS
create table public.logs (
  id bigint generated by default as identity primary key,
  park_id bigint references public.parks(id) on delete cascade not null,
  event_type text not null, -- entry, exit, alert
  description text,
  snapshot_url text,
  timestamp timestamp with time zone default timezone('utc'::text, now())
);

-- 7. ENABLE ROW LEVEL SECURITY (RLS)
-- Essential for security when using Supabase client on frontend
alter table public.profiles enable row level security;
alter table public.parks enable row level security;
alter table public.slots enable row level security;
alter table public.bookings enable row level security;
alter table public.logs enable row level security;

-- 8. RLS POLICIES (Basic Setup)

-- Profiles
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Parks
create policy "Parks are viewable by everyone." on public.parks for select using (true);
create policy "Owners can create parks." on public.parks for insert with check (auth.uid() = owner_id);
create policy "Owners can update own parks." on public.parks for update using (auth.uid() = owner_id);

-- Slots
create policy "Slots are viewable by everyone." on public.slots for select using (true);
create policy "Owners can manage slots." on public.slots for all using (
  exists (select 1 from public.parks where parks.id = slots.park_id and parks.owner_id = auth.uid())
);

-- Bookings
create policy "Users can view own bookings." on public.bookings for select using (auth.uid() = user_id);
create policy "Owners can view bookings for their parks." on public.bookings for select using (
  exists (select 1 from public.slots join public.parks on slots.park_id = parks.id 
          where slots.id = bookings.slot_id and parks.owner_id = auth.uid())
);
create policy "Users can create bookings." on public.bookings for insert with check (auth.uid() = user_id);

-- Logs
create policy "Owners can view logs." on public.logs for select using (
  exists (select 1 from public.parks where parks.id = logs.park_id and parks.owner_id = auth.uid())
);
